jamsgreatagain/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import urls as authurls
from django.contrib.auth import views as auth_views
from suggestionsapp import urls
from suggestionsapp import forms as app_forms

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^registration/', include('dappr.urls')),
    url(r'^auth/login/', auth_views.login,
        {'authentication_form': app_forms.BSLoginForm}),
    url(r'^auth/', include(authurls)),
    url(r'^', include(urls)),
]

makejamsgreat/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

suggestionsapp/urls.py
from django.conf.urls import url, include
from suggestionsapp import nav_urls
from suggestionsapp import views

urlpatterns = [
    url(r'^', include(nav_urls)),
    url(r'^detail/(?P<pk>\d+)/$', views.SuggestionDetailView.as_view(), name='suggestion-detail'),
]

suggestionsapp/models.py
from __future__ import unicode_literals
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from django.conf import settings
from django.utils.crypto import get_random_string


class Chatroom(models.Model):
    title = models.CharField(max_length=182) # The max length of a suggestion title, plus 12
    label = models.SlugField(unique=True, default=get_random_string())

    def __str__(self):
        return self.title


class Message(models.Model):
    room = models.ForeignKey(Chatroom, related_name='messages', on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text.strip()

class Suggestion(models.Model):
    title = models.CharField(max_length=170)
    description = models.TextField()
    upvoters = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='upvoters', blank=True)
    downvoters = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='downvoters', blank=True)
    votecount = models.IntegerField(default=0)
    chatroom = models.ForeignKey(Chatroom, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

    def upvote(self, user):
        # self.upvoters.add(user)
        self.votecount += 1
        self.save()

    def downvote(self, user):
        self.votecount -= 1
        self.save()


@receiver(post_save, sender=Suggestion)
def create_chatroom(sender, instance, created, **kwargs):
    """Create a matching profile whenever a user object is created."""
    if created:
        print 'created'
        chatroom_title = instance.title + ': Discussion'
        instance.chatroom = Chatroom.objects.create(title=chatroom_title)
        instance.save()

suggestionsapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from suggestionsapp import models


def pretty_name(name):
    """Converts 'first_name' to 'First name'"""
    if not name:
        return ''
    return name.replace('_', ' ').capitalize()


class PlaceholdersMixin(object):
    def __init__(self, *args, **kwargs):
        super(PlaceholdersMixin, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            if field:
                print field.widget
                if isinstance(field.widget, forms.TextInput) or isinstance(field.widget, forms.Textarea):
                    if field.label is not None:
                        field.widget.attrs['placeholder'] = unicode(field.label)
                    else:
                        field.widget.attrs['placeholder'] = unicode(pretty_name(field_name))
                    field.label = ""
                # Bootstrap thing
                field.widget.attrs['class'] = 'form-control'


class BootstrapClassMixin(object):
    def __init__(self, *args, **kwargs):
        super(BootstrapClassMixin, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            if isinstance(field.widget, forms.TextInput) or isinstance(field.widget, forms.Textarea):
                field.widget.attrs['class'] = 'form-control'
                if isinstance(field.widget, forms.Textarea):
                    del field.widget.attrs['cols']
                    del field.widget.attrs['rows']


class SuggestionModelForm(BootstrapClassMixin, forms.ModelForm):
    class Meta:
        model = models.Suggestion
        fields = ['title', 'description']


class PostMessageForm(BootstrapClassMixin, forms.ModelForm):
    class Meta:
        model = models.Message
        fields = ['text']

class BSLoginForm(BootstrapClassMixin, AuthenticationForm):
    pass

suggestionsapp/views.py
from django.views.generic import ListView, DetailView, CreateView, FormView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from suggestionsapp import models
from suggestionsapp import forms


class SuggestionsListView(ListView):
    SUGGESTIONS_DISPLAYED = 7
    model = models.Suggestion
    template_name = 'suggestionsapp/home.html'

    def get_queryset(self):
        if self.SUGGESTIONS_DISPLAYED == 'all':
            return models.Suggestion.objects.order_by('-votecount')
        else:
            return models.Suggestion.objects.order_by('-votecount')[:self.SUGGESTIONS_DISPLAYED]

    def get_context_data(self, **kwargs):
        context = super(SuggestionsListView, self).get_context_data(**kwargs)
        context['SUGGESTION_COUNT'] = models.Suggestion.objects.all().count()
        context['SUGGESTIONS_DISPLAYED'] = self.SUGGESTIONS_DISPLAYED
        return context

    def post(self, request, *args, **kwargs):
        obj = models.Suggestion.objects.get(pk=request.POST.get('pk'))
        if request.POST.get('method') == 'upvote':
            obj.upvote(request.user)
        elif request.POST.get('method') == 'downvote':
            obj.downvote(request.user)
        return HttpResponse('')


class FullSuggestionsListView(SuggestionsListView):
    template_name = 'suggestionsapp/all_suggestions.html'
    queryset = models.Suggestion.objects.order_by('-votecount')
    SUGGESTIONS_DISPLAYED = 'all'


class SuggestionDetailView(FormView, DetailView):
    model = models.Suggestion
    template_name = 'suggestionsapp/suggestion_detail.html'
    form_class = forms.PostMessageForm


class SuggestionCreateView(SuccessMessageMixin, CreateView):
    model = models.Suggestion
    template_name = 'suggestionsapp/create_suggestion.html'
    form_class = forms.SuggestionModelForm
    success_url = reverse_lazy('suggestions-partial-list')
    success_message = 'Suggestion posted!'

suggestionsapp/templates/suggestionsapp/add_comment_panel.html
<div class="well well-lg" id="add-comment-panel">
	<form id="add-comment-form">
		<h2 class="add-comment-title">Add a comment</h2>
		{{ form.as_p }}
		<input id="submit-comment-button" type="submit" value="Submit" class="btn btn-primary" ng-click="submitComment(this.parentNode)">
	</form>
</div>

suggestionsapp/templates/suggestionsapp/all_suggestions.html
{% extends "suggestionsapp/home.html" %}
{% block section_title %}
	All suggestions
{% endblock section_title %}
{% block jumbotron %}
	{# empty, because there is no jumbotron on this page #}
{% endblock jumbotron %}
{% block see_more_button %}
	{# empty, because there shouldn't be an all suggestions button #}
{% endblock see_more_button %}

suggestionsapp/templates/suggestionsapp/base_page.html
{% load pipeline %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>

	<style type="text/css">
		body {
		  padding-top: 50px;
		}
		.starter-template {
		  padding: 40px 15px;
		  /*text-align: center;*/
		}
	</style>
	{% stylesheet 'standard' %}
	{% javascript 'global' %}

	{% block stylesandjs %}
	{% endblock stylesandjs %}
	
	{% block extrahead %}		
	{% endblock extrahead %}
</head>
{% include "suggestionsapp/navbar.html" %}
<div class="container">
<main>
{% block content %}{% endblock %}
</main>
</div>

suggestionsapp/templates/suggestionsapp/create_suggestion.html
{% extends "suggestionsapp/base_page.html" %}
{% block content %}
<h1>
    Create a suggestion
</h1>
<form method="post" action="">
    {% csrf_token %}
    <div class="form-group">
        {{ form.as_p }}
    </div>
    <button type="submit" class="btn btn-primary">
        Submit
    </button>
</form>
{% endblock content %}

suggestionsapp/templates/suggestionsapp/home.html
{% extends "suggestionsapp/base_page.html" %}
{% load pipeline %}
{% block stylesandjs %}
{% javascript 'home' %}
{% endblock stylesandjs %}

{% block content %}

    {% block jumbotron %}
    <div class="jumbotron">
        <h1>Welcome!</h1>
        <p>Sampletext</p>
    </div>   
    {% endblock jumbotron %}
    <div id="floater-wrapper">
        <div class="alert alert-success" id="upvote-success-message">
            
            Upvote successful!
        </div>
        <div class="alert alert-success" id="downvote-success-message">
            Downvote successful!
        </div>
    </div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <h1>{% block section_title %}Top suggestions{% endblock %}</h1>
        <div class="list-group">
        {% for object in suggestion_list %}
            <span class="list-group-item">
                <a href="{% url 'suggestion-detail' pk=object.pk %}">
                    <span class="suggestion-preview-text">
                        <h2 class="list-group-item-heading">
                            {{ object.title }}
                        </h2>
                        <p class="list-group-item-text">
                            {{ object.description|truncatechars:75 }}
                        </p>
                    </span>
                </a>
                <span class="voting">
                    {% include "suggestionsapp/vote_widget.html" %}
                    <form class="vote-form upvote-form" method="post" action="" style="display:none">
                        {% csrf_token %}
                        <input type="hidden" name="pk" value="{{ object.pk }}">
                        <input type="hidden" name="method" value="upvote">
                    </form>
                    <form class="vote-form downvote-form" method="post" action="" style="display:none">
                        {% csrf_token %}
                        <input type="hidden" name="pk" value="{{ object.pk }}">
                        <input type="hidden" name="method" value="downvote">
                    </form>
                </span>
            </span>
        {% endfor %}
        {% if SUGGESTION_COUNT > SUGGESTIONS_DISPLAYED %}
            {% block see_more_button %}
            <a href="{% url 'suggestion-full-list' %}" class="list-group-item">
                {# This will be the "see more" button #}
                See more ({{ SUGGESTION_COUNT }} total)
            </a>
            {% endblock see_more_button %}

        {% endif %}
    </div>


{% endblock content %} 

suggestionsapp/templates/suggestionsapp/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Make JAMS Great Again!</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
      {% for nav_url in nav_urls %}
        <li>
          <a href="{% url nav_url.1.name %}">
            {{ nav_url.0 }}
          </a>
        </li>
      {% endfor %}
      <li id="login-button">
        <a href="{% url 'login' %}">{# -----Insert button here----- #}</a>
      </li>
      <li id="create-account-button">
        <a href="{% url 'registration_view' %}"><button class="btn btn-success" href="#">Create an account</button></a>
      </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
 

suggestionsapp/templates/suggestionsapp/suggestion_detail.html
{% extends "suggestionsapp/base_page.html" %}
{% load pipeline %}
{% block stylesandjs %}
  {% javascript 'detail' %}
{% endblock stylesandjs %}
{% block extrahead %}
<script>
var ctx = {
    CHATROOM_LABEL: '{{ object.chatroom.label }}',
    CHATROOM_MESSAGES: [
      {% for message in object.chatroom.messages.all %}
        '{{ message }}',
      {% endfor %}
    ],
};
</script>
{% endblock extrahead %}

{% block content %}
    {{ message }}
    <h1>{{ object.title }}</h1>
    {{ object.description }}
    <div class="panel panel-default" id="chatroom" ng-app="chatroom" ng-controller="chatroomController">
      <div class="panel-heading">
        <h3 class="panel-title">Discussion</h3>
      </div>
      <div class="panel-body">
        <div class="well well-sm" id="add-comment-button">
            <span class="glyphicon glyphicon-plus"></span>
            Add a comment
        </div>

        {% include "suggestionsapp/add_comment_panel.html" %}
        
        <template id="comment-panel-template">
          <div class="well well-sm">
            <span class="comment-text">
              {# comment text filled by js #}
            </span>
          </div>
        </template>
        <div id="comment-list">
          {# comments filled by js #}
        </div>

      </div>
    </div>
{% endblock content %}

suggestionsapp/templates/suggestionsapp/vote_widget.html
<div class="vote circle">
	<div class="increment up"></div>
	<div class="increment down"></div>
	<div class="count">{{ object.votecount }}</div>
</div>